
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 28 09:02:20 CET 2018
//----------------------------------------------------

package de.ovgu.spldev.featurecopp.lang.cpp;

/** CUP generated interface containing symbol constants. */
public interface ExpressionSymbols {
  /* terminals */
  public static final int T_ANTIV = 33;
  public static final int T_LOG_AND = 35;
  public static final int T_EQUIV = 32;
  public static final int T_INTEGER_LIT = 11;
  public static final int T_FUNMAC_ARG_NAMESPACE = 40;
  public static final int T_LPAR = 8;
  public static final int T_IFNDEF = 4;
  public static final int T_QM = 36;
  public static final int T_ELIF = 5;
  public static final int T_UPLUS = 15;
  public static final int T_GT = 29;
  public static final int T_LOG_NEG = 13;
  public static final int EOF = 0;
  public static final int T_MINUS = 16;
  public static final int T_AMP = 25;
  public static final int error = 1;
  public static final int T_DEFINED = 6;
  public static final int T_FUNMAC_ARG_LOC_HEADER = 39;
  public static final int T_GE = 31;
  public static final int T_MOD = 20;
  public static final int T_COMMA = 21;
  public static final int T_RPAR = 9;
  public static final int T_LSHIFT = 26;
  public static final int T_CARET = 23;
  public static final int T_FUNMAC_NO_PARENTHESES = 41;
  public static final int T_FUNMAC_ARG_GLOB_HEADER = 38;
  public static final int T_IDENTIFIER = 10;
  public static final int T_PLUS = 14;
  public static final int T_RSHIFT = 27;
  public static final int T_LT = 28;
  public static final int T_DIVIDE = 19;
  public static final int T_TILD = 24;
  public static final int T_IFDEF = 3;
  public static final int T_PIPE = 22;
  public static final int T_LOG_OR = 34;
  public static final int T_TIMES = 18;
  public static final int T_IF = 2;
  public static final int T_UMINUS = 17;
  public static final int T_CHAR_LIT = 7;
  public static final int T_COLON = 37;
  public static final int T_LE = 30;
  public static final int T_SHARP = 12;
}

