
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 28 12:44:01 CET 2018
//----------------------------------------------------

package de.ovgu.spldev.featurecopp.config;

/** CUP generated interface containing symbol constants. */
public interface ConfigSymbols {
  /* terminals */
  public static final int T_USER_ID = 7;
  public static final int T_ASPLIT = 23;
  public static final int T_ORIGINAL = 9;
  public static final int T_LOGPREFIX = 13;
  public static final int T_LOGROTATE = 14;
  public static final int T_MERGE = 24;
  public static final int T_RBRACE = 3;
  public static final int T_GLOBAL_ID = 6;
  public static final int T_LOGDIR = 12;
  public static final int T_FILETYPE = 10;
  public static final int T_ASSIGN = 5;
  public static final int T_REPORT = 20;
  public static final int EOF = 0;
  public static final int T_MODE = 15;
  public static final int T_INPUT = 8;
  public static final int T_DECIMAL_NUMBER = 19;
  public static final int T_BLACKLIST = 18;
  public static final int error = 1;
  public static final int T_LBRACE = 2;
  public static final int T_DEBUG = 16;
  public static final int T_STRING = 17;
  public static final int T_SPLIT = 21;
  public static final int T_AREPORT = 22;
  public static final int T_MACROPATTERN = 11;
  public static final int T_SEMI = 4;
}

