/* The following code was generated by JFlex 1.6.1 */

/* --------------------------Usercode Section------------------------ */
package de.ovgu.spldev.featurecopp.markup;

import java.nio.file.Path;
import de.ovgu.spldev.featurecopp.config.Configuration;
import de.ovgu.spldev.featurecopp.filesystem.Filesystem;
import java_cup.runtime.*;     

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/miniztree/Java-Development/_WORK/FeatureCOPP/specs/markup_analyzer/markup_analyzer.flex</tt>
 */
public class MarkupLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int VALUE = 2;
  public static final int CHAR_LIT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\25"+
    "\1\0\1\12\2\0\1\26\2\0\1\10\4\0\1\7\15\0\1\24"+
    "\2\0\1\11\1\0\1\0\1\0\1\0\1\0\1\0\1\0\1\0"+
    "\1\0\2\0\1\0\1\0\1\0\1\0\14\0\1\27\2\0\1\6"+
    "\1\0\1\0\1\0\1\17\1\20\1\5\3\0\1\13\1\0\1\0"+
    "\1\15\1\0\1\14\1\16\1\0\1\0\1\4\1\21\1\22\1\0"+
    "\1\23\1\0\1\0\14\0\1\0\u1fa2\0\1\0\1\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\3\1\1\3\1\4\4\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\13"+
    "\1\0\1\15\1\16\5\0\1\17\1\20\4\0\1\21"+
    "\1\22\11\0\1\23\1\24\6\0\1\25\1\0\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[60];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\30\0\60\0\110\0\140\0\110\0\170\0\220"+
    "\0\250\0\110\0\110\0\300\0\330\0\360\0\u0108\0\110"+
    "\0\110\0\u0120\0\110\0\110\0\u0138\0\110\0\110\0\u0150"+
    "\0\u0168\0\110\0\110\0\u0180\0\u0198\0\u01b0\0\u01c8\0\u01e0"+
    "\0\110\0\110\0\u01f8\0\u0210\0\u0228\0\u0240\0\110\0\110"+
    "\0\u0258\0\u0270\0\u0288\0\u02a0\0\u02b8\0\u02d0\0\u02e8\0\u0300"+
    "\0\u0318\0\110\0\110\0\u0330\0\u0348\0\u0360\0\u0378\0\u0390"+
    "\0\u03a8\0\110\0\u03c0\0\110";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[60];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\4\1\7\1\4\1\10\1\11"+
    "\1\12\1\13\1\14\2\4\1\15\1\4\1\16\1\17"+
    "\2\4\1\20\1\21\2\4\25\22\1\23\1\24\1\25"+
    "\26\26\1\27\1\30\32\0\1\6\41\0\1\31\23\0"+
    "\1\32\26\0\1\33\34\0\1\34\32\0\1\35\23\0"+
    "\1\36\5\0\1\37\12\0\1\40\23\0\25\22\30\0"+
    "\1\41\30\0\1\26\1\42\17\0\1\43\25\0\1\44"+
    "\31\0\1\45\14\0\1\46\45\0\1\47\24\0\1\50"+
    "\25\0\1\51\25\0\1\52\22\0\1\53\26\0\1\54"+
    "\30\0\1\55\35\0\1\56\26\0\1\57\33\0\1\60"+
    "\26\0\1\61\16\0\1\62\42\0\1\63\31\0\1\64"+
    "\24\0\1\65\23\0\1\66\33\0\1\67\33\0\1\70"+
    "\12\0\1\71\26\0\1\72\35\0\1\73\34\0\1\74"+
    "\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[984];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\3\1\2\11\4\1\2\11"+
    "\1\1\2\11\1\1\2\11\1\1\1\0\2\11\5\0"+
    "\2\11\4\0\2\11\11\0\2\11\6\0\1\11\1\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[60];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	// NOTE! any markup changes within Markup regarding used keywords (e.g. 'inline') have to be applied
	// to scanner specification below as well, since JFlex is not capable of using variables as macros/regexes
	public static class Markup {
		public static boolean isReference(final String markupLine) {
			return markupLine.matches("^/\\*\\$inline.*(\r|\n|\r\n)$");
		}
		public static boolean isBlock(final String markupLine) {
			return markupLine.matches("^/\\*@inline.*(\r|\n|\r\n)$");
		}
		public static boolean isEnd(final String line) {
			return line.matches("^/\\*@end\\*/.*(\r|\n|\r\n)$");
		}
		public static String genRefMarkup(long occ_id, long encl_occ_id, String file) {
			return genMarkup("$", "dst", occ_id, encl_occ_id, file)			
					+ "*/" + SRC_LINE_SEPARATOR;
		}
		public static String genBlockOpenMarkup(long occ_id, long encl_occ_id, String file, String directive) {
			return genMarkup("@", "src", occ_id, encl_occ_id, file)					
					+ MARKUP_DELIM
					+ "directive=\"" + directive + "\""
					+ "*/" + SRC_LINE_SEPARATOR;
		}
		private static String genMarkup(String head, String locator, long occ_id, long encl_occ_id, String file) {
			return "/*"
					+ head // $|@
					+ "inline"
					+ MARKUP_DELIM
					+ "occ_id=\""
					+ occ_id
					+ "\""
					+ MARKUP_DELIM
					+ "encl_occ_id=\""
					+ encl_occ_id
					+ "\""
					+ MARKUP_DELIM
					+ locator // src/dst
					+ "=\"" + file
					+ "\"";
		}			
		public static String genCloseMarkup() {
			return "/*@end*/" + SRC_LINE_SEPARATOR;
		}
		public Markup(long occ_id, long encl_occ_id, String file) {
			this.occ_id = occ_id;
			this.encl_occ_id = encl_occ_id;
			this.file = Filesystem.genPath(file);
		}
		@Override
		public String toString() {
			return "occ_id=[" + occ_id
					+ "];encl_occ_id=[" + encl_occ_id
					+ "];file=[" + file
					+ "]";
		}
		public Path getFile() {
			return file;
		}
		public long getOccId() {
			return occ_id;
		}
		protected long occ_id;
		protected long encl_occ_id;
		protected Path file;
		// permantently changed by CPP_ANALYZER -> markup should have same line terms as source
		public static String SRC_LINE_SEPARATOR = Configuration.LINE_SEPARATOR;
		private static final String MARKUP_DELIM = " ";
	}

	public static class MarkupBlock extends Markup {
		public MarkupBlock(long occ_id, long encl_occ_id, String file, String directive) {
			super(occ_id, encl_occ_id, file);
			this.directive = directive;
		}
		@Override
		public String toString() {
			return super.toString()
					+ ";directive=[" + directive + "]";
		}
		protected String directive;
	}
	MarkupLexer(boolean isDebug, java.io.Reader in) {
		this(in);
		this.isDebug = isDebug;
	}
	/** Reusable Lexer with changing java.io.Readers*/
	MarkupLexer() {

	}
	
	public static class MarkupLexerException extends Exception {
		public MarkupLexerException(String msg) {
			super(msg);
		}
	}
	public void setReader(java.io.Reader in) {
		zzReader = in;
	}
	/**
	 * if true, enables debug output, silencing otherwise
	 */
	public void debug(boolean isDebug) {
		this.isDebug = isDebug;
	}
    /* To create a new java_cup.runtime.Symbol with information about
       the current token, the token will have no value in this
       case. */
    private Symbol genSymbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }
    
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol genSymbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
        
    }
    // current markup characters are stored here (created at state change to value) 
    private StringBuffer currValue;
    private boolean isDebug = false;
    //private boolean isDebug = true;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MarkupLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return genSymbol(MarkupSymbols.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { yytext(); throw new java.io.IOException("Illegal character ["+yytext()+"] at line: "
			+ (yyline + 1)
			+ " column: " + (yycolumn + 1) + "!");
            }
          case 23: break;
          case 2: 
            { if(isDebug) {
			System.out.print(yytext());
		}
		// syntactically ignored
            }
          case 24: break;
          case 3: 
            { if(isDebug) {
			System.err.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_AT, yytext());
            }
          case 25: break;
          case 4: 
            { if(isDebug) {
			System.err.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_DOLLAR, yytext());
            }
          case 26: break;
          case 5: 
            { if(isDebug) {
			System.out.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_ASSIGN, yytext());
            }
          case 27: break;
          case 6: 
            { if(isDebug) {
			System.out.print(yytext());
		}
		currValue = new StringBuffer();
		yybegin(VALUE);
            }
          case 28: break;
          case 7: 
            { if(isDebug) {
			System.out.print(yytext());
		} 
		currValue.append( yytext() );
            }
          case 29: break;
          case 8: 
            { if(isDebug) {
			System.out.print(yytext());
		} 
		yybegin(YYINITIAL);
		return genSymbol(MarkupSymbols.T_VALUE, currValue.toString());
            }
          case 30: break;
          case 9: 
            { if(isDebug) {
			System.out.print(yytext());
		}
		currValue.append(yytext());
		yybegin(CHAR_LIT);
            }
          case 31: break;
          case 10: 
            { if(isDebug) {
			System.out.print(yytext());
		} 
    	currValue.append('\\');
            }
          case 32: break;
          case 11: 
            { if(isDebug) {
			System.out.print(yytext());
		}
		currValue.append(yytext());
            }
          case 33: break;
          case 12: 
            { if(isDebug) {
			System.out.print(yytext());
		}
		currValue.append(yytext());
		yybegin(VALUE);
            }
          case 34: break;
          case 13: 
            { if(isDebug) {
			System.err.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_COMM_BEGIN, yytext());
            }
          case 35: break;
          case 14: 
            { if(isDebug) {
			System.err.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_COMM_END, yytext());
            }
          case 36: break;
          case 15: 
            { if(isDebug) {
			System.out.print(yytext());
		} 
    	currValue.append('\"');
            }
          case 37: break;
          case 16: 
            { if(isDebug) {
			System.out.print(yytext());
		} 
    	currValue.append(yytext());
            }
          case 38: break;
          case 17: 
            { if(isDebug) {
			System.out.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_DST, yytext());
            }
          case 39: break;
          case 18: 
            { if(isDebug) {
			System.out.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_SRC, yytext());
            }
          case 40: break;
          case 19: 
            { if(isDebug) {
			System.err.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_INLINE, yytext());
            }
          case 41: break;
          case 20: 
            { if(isDebug) {
			System.err.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_OCC_ID, yytext());
            }
          case 42: break;
          case 21: 
            { if(isDebug) {
			System.out.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_DIRECTIVE, yytext());
            }
          case 43: break;
          case 22: 
            { if(isDebug) {
			System.err.print(yytext());
		}
		return genSymbol(MarkupSymbols.T_ENCL_OCC_ID, yytext());
            }
          case 44: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
