
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 28 10:15:15 CEST 2018
//----------------------------------------------------

package de.ovgu.spldev.featurecopp.markup;

/** CUP generated interface containing symbol constants. */
public interface MarkupSymbols {
  /* terminals */
  public static final int T_DIRECTIVE = 11;
  public static final int T_DST = 10;
  public static final int T_COMM_BEGIN = 2;
  public static final int T_ENCL_OCC_ID = 8;
  public static final int T_ASSIGN = 12;
  public static final int T_VALUE = 13;
  public static final int EOF = 0;
  public static final int T_AT = 4;
  public static final int T_COMM_END = 3;
  public static final int T_SRC = 9;
  public static final int T_OCC_ID = 7;
  public static final int error = 1;
  public static final int T_DOLLAR = 5;
  public static final int T_INLINE = 6;
}

